"""budget ledger cost reservations

Revision ID: 0005_budget_ledger
Revises: 0004_fencing
Create Date: 2026-09-05 19:38:45.766904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0005_budget_ledger'
down_revision: Union[str, None] = '0004_fencing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgetreservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_config_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reserved_input_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_output_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_cost_usd', sa.Float(), nullable=False),
    sa.Column('charged_input_tokens', sa.Integer(), nullable=False),
    sa.Column('charged_output_tokens', sa.Integer(), nullable=False),
    sa.Column('charged_cost_usd', sa.Float(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('usage_reported', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgetreservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgetreservation_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgetreservation_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgetreservation_stage_key'), ['stage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgetreservation_status'), ['status'], unique=False)

    with op.batch_alter_table('autonomousnoveljob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_input_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reserved_output_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reserved_cost_usd', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cost_unknown_calls', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('usage_estimated_calls', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('modelinvocationattempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_reported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelinvocationattempt', schema=None) as batch_op:
        batch_op.drop_column('max_tokens')
        batch_op.drop_column('usage_reported')

    with op.batch_alter_table('autonomousnoveljob', schema=None) as batch_op:
        batch_op.drop_column('usage_estimated_calls')
        batch_op.drop_column('cost_unknown_calls')
        batch_op.drop_column('cost_usd')
        batch_op.drop_column('reserved_cost_usd')
        batch_op.drop_column('reserved_output_tokens')
        batch_op.drop_column('reserved_input_tokens')

    with op.batch_alter_table('budgetreservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgetreservation_status'))
        batch_op.drop_index(batch_op.f('ix_budgetreservation_stage_key'))
        batch_op.drop_index(batch_op.f('ix_budgetreservation_stage'))
        batch_op.drop_index(batch_op.f('ix_budgetreservation_job_id'))

    op.drop_table('budgetreservation')
    # ### end Alembic commands ###
